//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TexiGen.rc
//
#define IDC_MYICON                      2
#define IDD_TEXIGEN_DIALOG              102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDS_GROUPSEL_TITLE              104
#define IDS_GRAPHSEL_TITLE              105
#define IDS_VARSEL_TITLE                106
#define IDI_TEXIGEN                     107
#define IDI_MAINFRAME                   107
#define IDS_SETSEL_TITLE                107
#define ID_GROUPERR1                    108
#define IDC_TEXIGEN                     109
#define IDM_SELECT                      109
#define IDA_MAIN                        109
#define ID_GROUPERR2                    110
#define IDM_EDIT                        110
#define ID_LOADERR1                     111
#define ID_LOADERR2                     111
#define IDM_EDIT_2                      111
#define ID_LOADERR                      112
#define IDM_EDIT2                       112
#define IDM_SELECT_2                    112
#define ID_LOADERR3                     113
#define IDM_SELECT2                     113
#define ID_LOADERR4                     114
#define ID_LOADERR5                     115
#define ID_LOADERR6                     116
#define ID_LOADERR7                     117
#define ID_LOADERR8                     118
#define IDS_OUTSEL_TITLE                119
#define ID_OUT_LIST                     120
#define ID_PROP_REPEAT                  120
#define ID_SELOUT                       121
#define ID_WIDTHOUT                     122
#define ID_HEIGHTOUT                    123
#define IDS_OUTWIDTH_TITLE              124
#define IDS_OUTHEIGHT_TITLE             125
#define ID_ANTIALIASING                 126
#define IDS_ZOOM_TITLE                  127
#define IDR_MAINFRAME                   128
#define ID_ZOOM                         128
#define IDB_SELECT                      129
#define ID_TILES                        129
#define IDD_NEWGROUP                    130
#define IDB_LEFT                        130
#define IDS_TILES_TITLE                 130
#define ID_GROUP_LIST                   131
#define IDB_RIGHT                       131
#define IDD_RENDER                      131
#define IDS_CONNECTED                   132
#define IDD_PROGRESS                    132
#define ID_PROP_CONNECTED               133
#define IDD_NEWFILTER                   133
#define ID_PROP_COLOR                   134
#define ID_LANGUAGE_CZ                  135
#define ID_LANGUAGE_EN                  136
#define ID_ABOUT                        137
#define ID_PROP_COLORR                  138
#define ID_PROP_COLORG                  139
#define ID_PROP_COLORB                  140
#define ID_PROP_COLORA                  141
#define ID_PROP_CHECK                   142
#define ID_PROP_CONNECTED2              143
#define ID_PROP_ENUM                    144
#define ID_PROP_VALUE                   145
#define ID_GENERATE                     146
#define ID_NEWGROUP                     147
#define ID_NEW                          148
#define ID_OPEN                         149
#define ID_DELETE                       150
#define ID_INFO                         151
#define ID_SAVE                         152
#define ID_RENDER                       153
#define ID_QUIT                         154
#define ID_SOUBOR_IMPLICITN155          155
#define ID_PROP_VALUE2                  155
#define ID_DEFAULT                      156
#define ID_CLOSE                        157
#define ID_SAVEVAR                      158
#define ID_SAVEAS                       159
#define ID_160                          160
#define ID_PROP_VALUE3                  160
#define ID_161                          161
#define ID_PROP_VALUE4                  161
#define ID_162                          162
#define ID_SAVEERR                      162
#define ID_Menu                         163
#define ID_SAVEERR2                     163
#define ID_164                          164
#define IDS_MODI                        164
#define ID_165                          165
#define IDS_MODI2                       165
#define ID_166                          166
#define IDS_CUSTOM                      166
#define ID_167                          167
#define IDS_FILEMASK                    167
#define ID_168                          168
#define IDS_PICMASK                     168
#define ID_IN_LABEL                     169
#define ID_IN_LABEL2                    170
#define IDS_MINIMUM                     171
#define IDS_MINIMUM2                    172
#define IDS_MAXIMUM                     173
#define IDS_MAXIMUM2                    174
#define ID_IN_VALUE                     175
#define IDS_VALUE2                      176
#define IDS_VALUE3                      177
#define IDS_VALUE4                      178
#define IDS_VALUE5                      179
#define ID_IN_COLOR                     180
#define ID_IN_COLOR2                    181
#define ID_UNDO                         182
#define IDS_COLORA                      182
#define ID_REDO                         183
#define IDS_COLORB                      183
#define ID_CUT                          184
#define IDS_COLORG                      184
#define ID_COPY                         185
#define IDS_COLORR                      185
#define ID_PASTE                        186
#define ID_IN_IMAGE                     186
#define ID_IN_IMAGE2                    187
#define ID_CLEAR                        188
#define ID_PROP_BRIGHT                  188
#define ID_ALL                          189
#define ID_PROP_CONTRAST                189
#define ID_CTRL_LOCK                    190
#define ID_FIND                         191
#define ID_CTRL_VALUE                   191
#define ID_CTRL_VALUE2                  192
#define ID_NEXT                         193
#define ID_CTRL_VALUE3                  193
#define ID_CTRL_VALUE4                  194
#define ID_CTRL_COLOR                   195
#define ID_CTRL_COLORA                  196
#define ID_CTRL_COLORB                  197
#define ID_CTRL_COLORG                  198
#define ID_CTRL_COLORR                  199
#define ID_CTRL_IMAGE                   200
#define ID_ZOBRAZEN200                  200
#define ID_CTRL_IMAGE2                  201
#define ID_SELDEL1                      202
#define ID_SELDEL2                      203
#define ID_SELDEL3                      204
#define ID_SELDEL4                      205
#define ID_CTRL_SWITCH                  206
#define ID_ZOBRAZEN206                  206
#define ID_CTRL_TILES                   207
#define ID_ZOBRAZEN207                  207
#define ID_CTRL_ENUM                    208
#define ID_ZOBRAZEN208                  208
#define ID_CTRL_MIN2                    209
#define ID_ZOBRAZEN209                  209
#define ID_CTRL_MAX                     210
#define ID_DIEWDOWN                     210
#define ID_CTRL_MAX2                    211
#define ID_211                          211
#define ID_CTRL_MIN                     212
#define ID_212                          212
#define ID_PROP_SOURCE                  213
#define ID_PROP_SOURCE2                 214
#define ID_PROP_SOURCE3                 215
#define ID_215                          215
#define ID_PROP_SOURCE4                 216
#define ID_216                          216
#define ID_PROP_SOURCE5                 217
#define ID_217                          217
#define ID_PROP_SOURCE6                 218
#define ID_SOUBOR_MUTACEVARIACE         218
#define ID_PROP_SOURCE7                 219
#define ID_PROP_SOURCE8                 220
#define ID_PROP_SOURCE9                 221
#define ID_PROP_SOURCE10                222
#define ID_PROP_OPACITY                 223
#define ID_PROP_BLENDMODE               224
#define ID_PROP_BRICK                   225
#define ID_VAR_VALUE                    226
#define ID_PROP_MORTAR                  227
#define ID_PROP_BRICKWIDTH              228
#define ID_PROP_BRICKHEIGHT             229
#define ID_PROP_BRICKGAP                230
#define ID_PROP_BRICKBEVEL              231
#define ID_PROP_BRICKCORNERS            232
#define ID_PROP_BRICKBOND               233
#define ID_PROP_BRICKCHAOS              234
#define ID_PROP_BRICKHUE                235
#define ID_PROP_BRICKSAT                236
#define ID_PROP_BRICKLUM                237
#define ID_PROP_SEED                    238
#define ID_PROP_BRICKFILL               239
#define ID_VAR_COLOR                    240
#define ID_VAR_IMAGE                    241
#define ID_CTRL_TEXT                    242
#define ID_IN_VALUE2                    243
#define ID_PROP_GAMMA                   244
#define ID_PROP_DETAILS                 245
#define ID_PROP_ROUGHNESS               246
#define ID_PROP_SCALE                   247
#define ID_PROP_SQUEEZE                 248
#define ID_PROP_ANGLE                   249
#define ID_PROP_SHIFTX                  250
#define ID_PROP_SHIFTY                  251
#define ID_PROP_SHIFTZ                  252
#define ID_PROP_NOISEHEIGHT             253
#define ID_PROP_NOISEPROFILE            254
#define ID_PROP_CELLULARCHAOS           255
#define ID_PROP_CELLULARSOLID           256
#define ID_PROP_CELLULARFORMULA         257
#define ID_PROP_CELLULARDIST            258
#define ID_PROP_CHECKWIDTH              259
#define ID_PROP_CHECKHEIGHT             260
#define ID_PROP_COLGRAD                 261
#define ID_PROP_COLRGRAD                262
#define ID_PROP_COLGGRAD                263
#define ID_PROP_COLBGRAD                264
#define ID_PROP_COLAGRAD                265
#define ID_PROP_CURBEG                  266
#define ID_PROP_CUREND                  267
#define ID_PROP_CURMIN                  268
#define ID_PROP_CURMAX                  269
#define ID_PROP_CURPOWER                270
#define ID_PROP_GAUSSWIDTH              271
#define ID_PROP_CURBIAS                 272
#define ID_PROP_CURGAIN                 273
#define ID_PROP_CURBALANCE              274
#define ID_PROP_CURPLATEAU              275
#define ID_PROP_CURSLOPE1               276
#define ID_PROP_CURSLOPE2               277
#define ID_PROP_CURSMOOTH               278
#define ID_PROP_CURSTEPS                279
#define IDS_LOCK_TITLE                  280
#define ID_LOCK                         281
#define ID_PROP_WAVES                   282
#define ID_PROP_RANDA                   283
#define ID_PROP_CURSLOPE                284
#define ID_PROP_SAWREVERSE              285
#define ID_PROP_RATIO                   286
#define ID_PROP_HUE                     287
#define ID_PROP_SAT                     288
#define ID_PROP_LUM                     289
#define ID_PROP_HSLHUE                  290
#define ID_PROP_HSLSAT                  291
#define ID_PROP_HSLLUM                  292
#define ID_PROP_ALPHA                   293
#define ID_PROP_GRANSTEPS               294
#define ID_PROP_MODSTEP                 295
#define ID_PROP_ADD                     296
#define ID_PROP_SUB                     297
#define ID_PROP_MUL                     298
#define IDP_FABS                        298
#define ID_PROP_DIV                     299
#define IDR_PREVIEW2                    299
#define IDP_FADD                        299
#define IDP_FABS1                       299
#define ID_PROP_EXP                     300
#define ID_PROP_RTOR                    301
#define ID_PROP_RTOG                    302
#define ID_PROP_RTOB                    303
#define ID_PROP_RTOA                    304
#define ID_PROP_GTOR                    305
#define ID_PROP_GTOG                    306
#define ID_PROP_GTOB                    307
#define ID_PROP_GTOA                    308
#define ID_PROP_BTOR                    309
#define ID_PROP_BTOG                    310
#define ID_PROP_BTOB                    311
#define ID_PROP_BTOA                    312
#define ID_PROP_ATOR                    313
#define ID_PROP_ATOG                    314
#define ID_PROP_ATOB                    315
#define ID_PROP_ATOA                    316
#define ID_PROP_RGBR                    317
#define ID_PROP_RGBG                    318
#define ID_PROP_RGBB                    319
#define ID_PROP_RGBA                    320
#define ID_PROP_ROTX                    321
#define ID_PROP_ROTY                    322
#define ID_PROP_SCALE2                  323
#define ID_PROP_STRETCHX                324
#define ID_PROP_STRETCHY                325
#define ID_PROP_SCALEX                  326
#define ID_PROP_SCALEY                  327
#define ID_PROP_SHEAR                   328
#define ID_PROP_SHEARCENTER             329
#define ID_PROP_SWITCHR                 330
#define ID_PROP_SWITCHG                 331
#define ID_PROP_SWITCHB                 332
#define ID_PROP_SWITCHA                 333
#define ID_PROP_SWITCH                  334
#define ID_GRAPHERR1                    335
#define ID_GRAPHERR2                    336
#define ID_GRAPHERR3                    337
#define ID_SELDEL5                      338
#define ID_SELDEL6                      339
#define ID_SELDEL7                      340
#define ID_CTRL_MINVAL                  341
#define ID_CTRL_MINVAL2                 342
#define ID_CTRL_MAXVAL                  343
#define ID_CTRL_MAXVAL2                 344
#define ID_CTRL_MAX4                    344
#define ID_PROP_HEIGHTMAP               345
#define ID_PROP_ENVIRONMENT             346
#define ID_PROP_EMBOSSDIF               347
#define ID_PROP_BUMPINESS               347
#define ID_PROP_DIFFUSE                 348
#define ID_PROP_AMBIENT                 349
#define ID_PROP_SPECULAR                350
#define ID_PROP_METAL                   351
#define ID_PROP_EMBOSSSIZE              352
#define ID_PROP_EMBOSSSAT               352
#define ID_PROP_RADIUSX                 353
#define ID_PROP_CACHEWIDTH              354
#define ID_PROP_CACHEHEIGHT             355
#define ID_PROP_POINTS                  356
#define ID_PROP_TILED                   357
#define ID_PROP_STRENGTH                358
#define ID_PROP_EMBBASE                 359
#define ID_PROP_RADIUSY                 360
#define ID_OUT_LABEL                    361
#define ID_PROP_RADIUS                  362
#define ID_PROP_RADIUSY2                362
#define ID_OUT_LABEL2                   363
#define ID_PROP_WIDTH                   364
#define ID_PROP_HEIGHT                  365
#define ID_PROP_ANGLE2                  366
#define IDD_INFO                        367
#define ID_PROP_TILES                   367
#define ID_FLIP_ANGLE                   368
#define ID_LENS_DIAMETER                369
#define ID_LENS_REFRACTION              370
#define ID_PROP_BLENDX                  371
#define ID_PROP_BLENDY                  372
#define ID_PROP_BLENDX2                 372
#define ID_ZOOMIN                       373
#define ID_ZOOMOUT                      374
#define ID_SELZOOM                      375
#define IDR_RPATH                       376
#define IDS_ZOOMSEL_TITLE               376
#define ID_VIEWLEFT                     377
#define ID_VIEWRIGHT                    378
#define ID_VIEWUP                       379
#define ID_VIEWDOWN                     380
#define ID_PROP_EMBOSSSCALE             381
#define ID_SMOOTH_RADIUS                382
#define ID_SMOOTH_POINTS                383
#define ID_PROP_KALEIDMODE              384
#define ID_PROP_GRAD                    385
#define ID_PROP_RADIALX                 386
#define ID_PROP_RADIALY                 387
#define ID_PROP_RADIALW                 388
#define ID_PROP_RADIALH                 389
#define ID_PROP_RADIALW2                389
#define ID_PROP_CITYCHAOS               390
#define IDS_PRIOROTY                    391
#define IDS_PRIORITY                    391
#define ID_PROP_PAVINGWIDTH             392
#define ID_PROP_PAVINGHEIGHT            393
#define ID_PROP_PAVINGBOND              394
#define ID_PROP_BRICKBOND2              394
#define ID_CONTOUR_RADIUS               395
#define IDS_THREADS                     396
#define ID_TABLE_LABEL                  397
#define ID_TABLE_LABEL2                 398
#define ID_PROP_ANGLE3                  399
#define ID_PROP_WOODFIBERS              400
#define ID_PROP_WOODDENS                401
#define ID_PROP_WOODSMOOTH              402
#define ID_PROP_WOODRINGS               403
#define ID_PROP_ANGULARMIRROR           404
#define ID_BRICK_LABEL                  405
#define ID_BRICK_LABEL2                 406
#define ID_PROP_PARTCHANCE2             407
#define ID_PROP_PARTCHANCE3             408
#define ID_PROP_PARTCHANCE4             409
#define ID_PROP_PARTCHANCE5             410
#define ID_PROP_PARTBACK                411
#define ID_PROP_PARTANGLE               412
#define ID_PROP_PARTSIZE                413
#define ID_PROP_PARTSQUASH              414
#define ID_PROP_PARTPOSX                415
#define ID_PROP_PARTPOSY                416
#define ID_PROP_PARTOPACITY             417
#define ID_PROP_PARTBLEND               418
#define ID_PROP_PARTCHANCE1             419
#define ID_PROP_PARTTINTCOL             420
#define ID_PROP_PARTTINT                421
#define ID_PROP_PARTRNDOPACITY          422
#define ID_PROP_PARTRNDSIZE             423
#define ID_PROP_PARTRNDANGLE            424
#define ID_PROP_PARTRNDPOSX             425
#define ID_PROP_PARTRNDPOSY             426
#define ID_PROP_PARTRNDSQUASH           427
#define ID_PROP_PARTRNDTINT             428
#define ID_PROP_PARTTINTMODE            428
#define ID_PROP_PARTRNDHUE              429
#define ID_PROP_PARTRNDSAT              430
#define ID_PROP_PARTRNDLUM              431
#define ID_PROP_BEVEL                   432
#define ID_PROP_BEVELPROFILE            433
#define ID_PROP_BEZIERX1                434
#define ID_PROP_BEZIERY1                435
#define ID_PROP_BEZIERA1                436
#define ID_PROP_BEZIERS1                437
#define ID_PROP_BEZIERX2                438
#define ID_PROP_BEZIERY2                439
#define ID_PROP_BEZIERA2L               440
#define ID_PROP_BEZIERS2L               441
#define ID_PROP_BEZIERA2R               442
#define ID_PROP_BEZIERS2B               443
#define ID_PROP_BEZIERS2R               443
#define ID_PROP_BEZIERX3                444
#define ID_PROP_BEZIERY3                445
#define ID_PROP_BEZIERA3                446
#define ID_PROP_BEZIERS3                447
#define ID_PROP_BACKGROUND              448
#define ID_PROP_BOXCOLOR                449
#define ID_PROP_STARRAYS                450
#define ID_PROP_STARRADIUS              451
#define ID_PROP_STARSTUFFING            452
#define ID_PROP_STARSPLATOUT            453
#define ID_PROP_STARSMOOTH              454
#define ID_PROP_STARSMOOTHIN            455
#define ID_PROP_STARSPLATIN             456
#define ID_PROP_CORNERS                 457
#define ID_PROP_BRICKCORNERS2           457
#define ID_PROP_CARDCOLOR               458
#define ID_PROP_CARD                    458
#define ID_PROP_CARDVALUE               459
#define IDS_INTERROR                    459
#define ID_PROP_CARDOUTLINE             460
#define ID_PROP_CARDOUTCOL              461
#define ID_PROP_HOLE                    462
#define ID_PROP_LTSCALE                 463
#define ID_PROP_LTANGLE                 464
#define ID_PROP_LTINTENS                465
#define ID_PROP_METALSCALE              466
#define ID_PROP_METALDENS               467
#define ID_PROP_METALANGLE              468
#define ID_PROP_METALCONT               469
#define ID_PROP_METALWAVES              470
#define ID_PROP_TRIX1                   471
#define ID_PROP_TRIX2                   472
#define ID_PROP_TRIX3                   473
#define ID_PROP_TRIY1                   474
#define ID_PROP_TRIY2                   475
#define ID_PROP_TRIY3                   476
#define ID_PROP_THRESLEVEL              477
#define ID_PROP_THRESTOL                478
#define ID_PROP_THRESLOW                479
#define ID_PROP_THRESHIGH               480
#define ID_PROP_FLOORTILES              481
#define ID_PROP_FLOORDIAG               482
#define ID_PROP_INTMIN                  483
#define ID_PROP_INTMAX                  484
#define ID_PROP_INTMIN2                 484
#define ID_PROP_LOOPBEGIN               485
#define ID_PROP_LOOPEND                 486
#define ID_LOOP_LABEL                   487
#define ID_PROP_EGGSHAPE                487
#define ID_LOOP_LABEL2                  488
#define ID_PROP_LOOPNUM                 488
#define ID_PROP_TAPERX                  489
#define ID_PROP_TAPERY                  490
#define ID_PROP_TAPERX2                 491
#define ID_PROP_TAPERY2                 492
#define ID_PROP_EGGSHIFT                493
#define ID_PROP_EGGSIZE                 494
#define ID_PROP_EGGMIRROR               495
#define ID_PROP_GRANNOISE               496
#define ID_PROP_GRANNOISESCALE          497
#define ID_PROP_GRAINCOLOR              498
#define ID_PROP_GRAINCONTR              499
#define ID_PROP_GRAINLEVEL              500
#define ID_PROP_GRAINSCALE              501
#define ID_PROP_GRANCOLOR               502
#define ID_PROP_GRANCONTRAST            503
#define ID_PROP_GRANLEVEL               504
#define ID_PROP_GRANROUGH               505
#define ID_PROP_GRANSCALE               506
#define ID_PROP_GRANSMOOTH              507
#define ID_PROP_WEBCONTR                508
#define ID_PROP_WEBGAMMA                509
#define ID_COPYPAR                      510
#define ID_PASTEPAR                     511
#define ID_COPYVAR                      512
#define ID_PASTEVAR                     513
#define ID_PROP_GLASSCONTR              514
#define ID_PROP_GLASSSCALE              515
#define ID_PROP_GLASSDENS               516
#define ID_PROP_GLASSBUMP               517
#define ID_PROP_GLASSBSCALE             518
#define ID_PROP_WARP                    519
#define ID_PROP_MARSMUDGES              520
#define ID_PROP_MALACHRINGS             521
#define ID_PROP_MALACHDENS              522
#define ID_PROP_CRACKSTHIN              523
#define ID_PROP_CRACKSLAYERS            524
#define ID_PROP_CRACKSLEVEL             525
#define ID_RENUM                        526
#define ID_PROP_MOSAICFILL              527
#define ID_PROP_FLOORFILL               528
#define ID_PROP_BRICKFILL2              528
#define ID_PROP_BEVELMODE               529
#define ID_PROP_GLASSREFL               530
#define ID_PROP_MATMODE                 531
#define ID_PROP_CONTRAST2               532
#define ID_PROP_ROUGHNESS2              533
#define ID_PROP_FABRICWIDTH             534
#define ID_PROP_FABRICHEIGHT            535
#define ID_PROP_EMBOSS                  536
#define ID_PROP_SHAPEMODE               537
#define ID_PROP_JINJANGCIRCLE           538
#define ID_PROP_ROSEDETAILS             539
#define ID_PROP_DANDRAYS                540
#define ID_PROP_BLADEWIDTH              541
#define ID_PROP_BLADEWARP               542
#define ID_PROP_SEWBTN_SIZEOUT          543
#define ID_PROP_SEWBTN_SIZEIN           544
#define IDR_REFLECT1                    544
#define ID_PROP_SEWBTN_SIZEHOLE         545
#define IDB_ICON256                     545
#define ID_PROP_SEWBTN_BEVELOUT         546
#define IDB_ICON16                      546
#define ID_PROP_SEWBTN_BEVELIN          547
#define IDB_ICON32                      547
#define ID_PROP_SEWBTN_BEVELHOLE        548
#define IDB_ICON48                      548
#define ID_PROP_SEWBTN_DISTHOLE         549
#define IDB_ICON64                      549
#define ID_PROP_COLORIN                 550
#define IDB_BITMAP6                     550
#define IDB_ICON128                     550
#define ID_PROP_COLOROUT                551
#define ID_PROP_CLIPTHICK               552
#define IDR_LICENSE                     552
#define ID_PROP_CLIPSIZE                553
#define IDR_LICENSE1                    553
#define ID_PROP_DIV2                    554
#define ID_GENERATE2                    555
#define IDS_PRIORITY2                   555
#define ID_PROP_RNDMIN                  555
#define ID_PROP_RNDMAX                  556
#define ID_PROP_PARTICLE                557
#define ID_MARK_VAR                     558
#define ID_MARK_ALL                     559
#define ID_MUTATE                       560
#define ID_MARK_ALL2                    561
#define ID_MARK_ALL3                    562
#define ID_PROP_PERCENTILE              563
#define ID_PROP_PERCRGB                 564
#define ID_PROP_LOOKUPX                 565
#define ID_PROP_LOOKUPY                 566
#define IDS_TIME_TITLE                  567
#define ID_TIME                         568
#define ID_PROP_HPLUMIN                 569
#define ID_PROP_TIMEPROFILE             570
#define ID_PROP_BEVELPROFILE2           570
#define ID_PROP_GAIN                    571
#define ID_AUTOGENER                    572
#define ID_CTRL_IMAGE3                  573
#define ID_LOCKINV                      574
#define IDS_PICMASK2                    575
#define ID_PROP_ALPHAMOD                576
#define ID_PROP_TUSRNDCOL               577
#define ID_PROP_TUSRNDSIZE              578
#define ID_PROP_TUSCOUNT                579
#define ID_PROP_TUSRANGE                580
#define ID_PROP_TUSSHADOWS              581
#define ID_PROP_TUSSHDWSHFT             582
#define ID_PROP_TUSFAN                  583
#define ID_PROP_CUTX1                   584
#define ID_PROP_CUTX2                   585
#define ID_PROP_CUTY1                   586
#define ID_PROP_CUTY2                   587
#define ID_HELP_ERR                     588
#define ID_HELP_ERR2                    589
#define ID_HELP_FILENAME                590
#define ID_PROP_DEFORMX1                591
#define ID_PROP_DEFORMY1                592
#define ID_PROP_DEFORMX2                593
#define ID_PROP_DEFORMY2                594
#define ID_PROP_DEFORMX3                595
#define ID_PROP_DEFORMY3                596
#define ID_PROP_DEFORMX4                597
#define ID_PROP_DEFORMY4                598
#define ID_PROP_BACKGROUND2             599
#define ID_PROP_BACKFACE                599
#define IDP_FALPHA                      600
#define ID_PROP_MANDSTEPS               600
#define ID_PROP_MANDELSMOOTH            601
#define ID_PROP_JULIAKR                 602
#define ID_PROP_JULIAKI                 603
#define ID_PROP_JULIA                   604
#define ID_PROP_MANDELFORMULA           604
#define ID_PROP_JULIAMODE               614
#define IDC_NAME                        1001
#define IDC_WIDTH                       1003
#define IDC_HEIGHT                      1004
#define IDC_PRESET                      1006
#define IDC_ANTI                        1007
#define IDC_OUTPUT                      1012
#define IDC_FILE                        1013
#define IDC_BROWSE                      1014
#define IDC_PROGRESS                    1015
#define IDC_ELAPSED                     1016
#define IDC_REMAIN                      1017
#define IDC_TRANS                       1018
#define IDC_INQUEUE                     1018
#define IDC_PAUSE                       1020
#define IDC_DUPLICATE                   1021
#define IDC_EDIT                        1024
#define IDC_CONTINUE                    1026
#define IDC_PRIORITY                    1027
#define IDCANCEL2                       1028
#define IDC_THREADS                     1029
#define IDC_LATER                       1029
#define IDC_QUEUE                       1030
#define IDC_CLEAR                       1032
#define IDC_AUTO                        1033
#define IDC_VERSION                     1034
#define IDC_WEB                         1035
#define IDC_HOME                        1036
#define IDC_EMAIL                       1037
#define IDC_EDIT2                       1038
#define IDC_EMAIL2                      1038
#define IDC_FROM                        1038
#define IDC_LICENSE                     1040
#define IDC_PORTFOLIO                   1041
#define IDC_COPYRIGHT                   1042
#define IDC_AUTOCHECK                   1043
#define IDC_QUEUEON                     1044
#define IDC_QSTART                      1045
#define IDC_QUP                         1046
#define IDC_QDOWN                       1047
#define IDC_QCLEAR                      1048
#define IDC_TIMEALL                     1049
#define IDC_QLOAD                       1050
#define IDC_TIME                        1051
#define IDC_TOTAL                       1052
#define IDC_FRAMES                      1054
#define IDC_TO                          1055
#define IDC_JPG                         1056
#define IDC_JPGSLIDER                   1057
#define IDC_JPGQUALITY                  1058
#define ID_PREV_IDLE                    2007
#define ID_PREV_LOWEST                  2008
#define ID_PREV_VERYLOW                 2009
#define ID_PREV_LOW                     2010
#define ID_PREV_LOWER                   2011
#define ID_PREV_NORMAL                  2012
#define ID_PREV_STOP                    2013
#define ID_PREV_OFF                     2014
#define ID_PREV_DIM0                    2014
#define ID_PREV_DIM1                    2015
#define ID_PREV_DIM2                    2016
#define ID_PREV_DIM3                    2017
#define ID_MARK                         2018
#define ID_PREV_DIM4                    2018
#define ID_PREV_DIM5                    2019
#define ID_PREV_DIM6                    2020
#define ID_PREV_DIM7                    2021
#define ID_PREV_DIM8                    2022
#define ID_PREV_DIM9                    2023
#define ID_PREV_DIM20                   2024
#define ID_PREV_DIM21                   2025
#define ID_PREV_DIM22                   2026
#define ID_PREV_DIM23                   2027
#define ID_2031                         2031
#define ID_N2032                        2032
#define ID_HELP                         2033
#define ID_HELP_CONTENT                 2034
#define ID_N2037                        2037
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        615
#define _APS_NEXT_COMMAND_VALUE         2038
#define _APS_NEXT_CONTROL_VALUE         1060
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
