@echo off
echo x >> x.tga
call !_.bat 001
if not exist x.tga goto konec
call !_.bat 002
if not exist x.tga goto konec
call !_.bat 003
if not exist x.tga goto konec
call !_.bat 004
if not exist x.tga goto konec
call !_.bat 005
if not exist x.tga goto konec
call !_.bat 006
if not exist x.tga goto konec
call !_.bat 007
if not exist x.tga goto konec
call !_.bat 008
if not exist x.tga goto konec
call !_.bat 009
if not exist x.tga goto konec
call !_.bat 010
if not exist x.tga goto konec
call !_.bat 011
if not exist x.tga goto konec
call !_.bat 012
if not exist x.tga goto konec
call !_.bat 013
if not exist x.tga goto konec
call !_.bat 014
if not exist x.tga goto konec
call !_.bat 015
if not exist x.tga goto konec
call !_.bat 016
if not exist x.tga goto konec
call !_.bat 017
if not exist x.tga goto konec
call !_.bat 018
if not exist x.tga goto konec
call !_.bat 019
if not exist x.tga goto konec
call !_.bat 020
if not exist x.tga goto konec
call !_.bat 021
if not exist x.tga goto konec
call !_.bat 022
if not exist x.tga goto konec
call !_.bat 023
if not exist x.tga goto konec
call !_.bat 024
if not exist x.tga goto konec
call !_.bat 025
if not exist x.tga goto konec
call !_.bat 026
if not exist x.tga goto konec
call !_.bat 027
if not exist x.tga goto konec
call !_.bat 028
if not exist x.tga goto konec
call !_.bat 029
if not exist x.tga goto konec
call !_.bat 030
if not exist x.tga goto konec
call !_.bat 031
if not exist x.tga goto konec
call !_.bat 032
if not exist x.tga goto konec
call !_.bat 033
if not exist x.tga goto konec
call !_.bat 034
if not exist x.tga goto konec
call !_.bat 035
if not exist x.tga goto konec
call !_.bat 036
if not exist x.tga goto konec
call !_.bat 037
if not exist x.tga goto konec
call !_.bat 038
if not exist x.tga goto konec
call !_.bat 039
if not exist x.tga goto konec
call !_.bat 040
if not exist x.tga goto konec
call !_.bat 041
if not exist x.tga goto konec
call !_.bat 042
if not exist x.tga goto konec
call !_.bat 043
if not exist x.tga goto konec
call !_.bat 044
if not exist x.tga goto konec
call !_.bat 045
if not exist x.tga goto konec
call !_.bat 046
if not exist x.tga goto konec
call !_.bat 047
if not exist x.tga goto konec
call !_.bat 048
:konec
