OLD=    ega16.grd trid8916.grd trid89n.grd tseng416.grd tseng4kn.grd vga16.grd

NEW=    stdvga.grn stdega.grn et4000.grn tr8900.grn ativga.grn stealth.grn

SPEC=   atiultra.grn vesainfo.com modetest

todo:   all clean

all:    $(OLD) $(NEW) $(SPEC)

clean:
        del *.obj
        del *.exe
        del *.map

realclean: clean
        del *.com
        del *.gr?
        del modetest

.asm.grd:
        tasm $*.asm
        tlink $*.obj;
        exe2bin $*.exe $*.grd

.asm.grn:
        tasm $*.asm
        tlink $*.obj;
        exe2bin $*.exe $*.grn

atiultra.grn: atiultra.asm grdriver.inc ibm8514a.c reg8514a.h
        tcc -c -w -ms! -u- -v -O ibm8514a.c
        tasm /ml atiultra.asm
        tlink /c /i /m /s atiultra.obj ibm8514a.obj, atiultra.exe, atiultra.map
        exe2bin atiultra.exe atiultra.grn

vesainfo.com: vesainfo.c
        tcc -mt -w -O -G -Z vesainfo.c
        exe2bin vesainfo.exe vesainfo.com

modetest: modetest.c ../lib/libgrx.a ../include/grx.h
        gcc -o modetest -L../lib modetest.c -lgrx


$(OLD): grdriver.inc

$(NEW): grdriver.inc


