
; -----------------------------------------------------------------------------
; -----------------------------------------------------------------------------

         .z80

; ------ definice z sobn¡ku

Start:   ld        sp,Stack

         bit       0,(ix+4)
         ld        (ix+128),34h
         ld        a,(iy+12)

; ------ zobrazen¡ £vodn¡ho textu

         ld        de,UvText
         call      DispTxt
         jp        0

UvText:  defm      '€esk˜ text - h ‡ky a ‡ rky.',13,10,"$"

; -----------------------------------------------------------------------------
;        zobrazen¡ textu DE
; -----------------------------------------------------------------------------

DispTxt: push      bc
         ld        c,9
         call      5
         pop       bc
         ret

         ds        200
Stack:   ds        20

         END       Start
