
copy /b tuv24.txt prn
copy /b roman24.sfp prn
copy /b tzaver.txt prn

copy /b tuv24o.txt prn
copy /b roman24o.sfp prn
copy /b tzaver.txt prn

copy /b tuv24s.txt prn
copy /b roman24s.sfp prn
copy /b tzaver.txt prn


copy /b tuv12.txt prn
copy /b roman12.sfp prn
copy /b tzaver.txt prn

copy /b tuv12o.txt prn
copy /b roman12o.sfp prn
copy /b tzaver.txt prn

copy /b tuv12s.txt prn
copy /b roman12s.sfp prn
copy /b tzaver.txt prn


copy /b tuv6.txt prn
copy /b roman6.sfp prn
copy /b tzaver.txt prn

copy /b tuv6o.txt prn
copy /b roman6o.sfp prn
copy /b tzaver.txt prn

copy /b tuv6s.txt prn
copy /b roman6s.sfp prn
copy /b tzaver.txt prn


copy /b ascii prn
